version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=jobboard
      - POSTGRES_USER=dapo
      - POSTGRES_PASSWORD=hellothere
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dapo -d jobboard"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build: ./jobboard_backend
    ports:
      - "8000:8000"
    env_file:
      - ./jobboard_backend/.env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./jobboard_backend:/app

  # Nuxt.js Frontend
  frontend:
    build: 
      context: ./job-board
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - BACKEND_URL=http://backend:8000
    volumes:
      - ./job-board:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data:
