FROM python:3.9-slim

# Install system dependencies
RUN apt-get update \
    && apt-get install -y libpq-dev gcc postgresql-client curl \
    && apt-get clean

WORKDIR /app

# Copy requirements first for caching
# COPY requirements.txt .
# RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY . .

# Make wait-for script executable
COPY wait-for.sh .
RUN chmod +x wait-for.sh

# Expose port
EXPOSE 8000

# Wait for DB and run migrations before starting
ENTRYPOINT ["./wait-for.sh"]

# Add healthcheck
HEALTHCHECK --interval=30s --timeout=10s --start-period=30s --retries=3 \
    CMD curl -f http://localhost:8000/api/v1/jobapp/health/ || exit 1