# Generated by Django 4.2.17 on 2025-04-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0002_jobapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="availability",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="company_industry",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="company_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="company_logo",
            field=models.ImageField(blank=True, null=True, upload_to="company_logos/"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="company_website",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="experience_level",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="github_link",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="portfolio_file",
            field=models.FileField(blank=True, null=True, upload_to="portfolios/"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="portfolio_link",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="skills",
            field=models.TextField(blank=True, null=True),
        ),
    ]
