# Generated by Django 4.2.17 on 2025-04-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0004_customuser_education_degree_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="education_years",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="english_level",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="hours_per_week",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
