# Generated by Django 4.2.17 on 2025-04-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0008_jobapplication_via_invite_jobinvite"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="new_applications_count",
            field=models.IntegerField(default=0),
        ),
    ]
