# Generated by Django 4.2.17 on 2025-04-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0009_job_new_applications_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="skills_needed",
            field=models.TextField(blank=True, null=True),
        ),
    ]
