# Generated by Django 4.2.17 on 2025-04-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0010_job_skills_needed"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="delivery_time",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
