# Generated by Django 4.2.17 on 2025-04-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0011_job_delivery_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="reset_password_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="reset_password_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
