# Generated by Django 4.2.17 on 2025-04-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0012_customuser_reset_password_expiry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
