# Generated by Django 4.2.17 on 2025-04-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0013_customuser_deleted_at_customuser_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("archived", "Archived"),
                    ("completed", "Completed"),
                    ("deleted", "Deleted"),
                    ("paused", "Paused"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
