# Generated by Django 4.2.17 on 2025-04-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0014_job_deleted_at_job_is_deleted_job_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="deleted_at",
            new_name="archived_at",
        ),
        migrations.RemoveField(
            model_name="job",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="job",
            name="archived_reason",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("archived", "Archived"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
