# Generated by Django 4.2.17 on 2025-04-26 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0016_contract_milestone_payment_wallet_wallettransaction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="jobapp.jobapplication",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("contract_funding", "Contract Funding"),
                    ("milestone_funding", "Milestone Funding"),
                    ("milestone_release", "Milestone Release"),
                    ("withdraw", "Withdrawal"),
                    ("wallet_funding", "Wallet Funding"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("credit", "Credit"),
                    ("debit", "Debit"),
                    ("escrow_hold", "Escrow Hold"),
                    ("escrow_release", "Escrow Release"),
                ],
                max_length=15,
            ),
        ),
    ]
