# Generated by Django 4.2.17 on 2025-04-27 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0017_alter_contract_application_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="paystack_access_code",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="paystack_authorization_url",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="paystack_reference",
        ),
        migrations.AddField(
            model_name="payment",
            name="expected_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="gateway_response",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="status_history",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="History of status changes",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="is_successful",
            field=models.BooleanField(
                default=True, help_text="Whether the transaction was successful"
            ),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="reference",
            field=models.CharField(
                blank=True,
                help_text="Unique reference for this transaction",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="jobapp.contract",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="milestone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="jobapp.milestone",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("contract_funding", "Contract Funding"),
                    ("milestone_payment", "Milestone Payment"),
                    ("wallet_funding", "Wallet Funding"),
                    ("withdrawal", "Withdrawal"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="recipient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="reference",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
