# Generated by Django 4.2.17 on 2025-04-29 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0018_remove_payment_paystack_access_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="expected_amount",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="gateway_response",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="status_history",
        ),
        migrations.RemoveField(
            model_name="wallettransaction",
            name="is_successful",
        ),
        migrations.RemoveField(
            model_name="wallettransaction",
            name="reference",
        ),
        migrations.AddField(
            model_name="payment",
            name="paystack_access_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="paystack_authorization_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="paystack_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="jobapp.contract",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="milestone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="jobapp.milestone",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("contract_funding", "Contract Funding"),
                    ("milestone_funding", "Milestone Funding"),
                    ("milestone_release", "Milestone Release"),
                    ("withdraw", "Withdrawal"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="recipient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="reference",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("credit", "Credit"), ("debit", "Debit")], max_length=10
            ),
        ),
    ]
