# Generated by Django 4.2.17 on 2025-04-29 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0019_remove_payment_expected_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="reference",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
