# Generated by Django 4.2.17 on 2025-04-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0020_auto_20250429_0305"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="reference",
            field=models.CharField(
                blank=True,
                help_text="Unique reference ID for the payment",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
