# Generated by Django 4.2.17 on 2025-04-29 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0022_auto_20250429_0331"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contractfile",
            name="contract",
        ),
        migrations.RemoveField(
            model_name="contractfile",
            name="uploaded_by",
        ),
        migrations.RemoveField(
            model_name="contractmessage",
            name="contract",
        ),
        migrations.RemoveField(
            model_name="contractmessage",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="milestone",
            name="contract",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="contract",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="milestone",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="payer",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="recipient",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="user",
        ),
        migrations.RemoveField(
            model_name="wallettransaction",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="wallettransaction",
            name="wallet",
        ),
        migrations.DeleteModel(
            name="Contract",
        ),
        migrations.DeleteModel(
            name="ContractFile",
        ),
        migrations.DeleteModel(
            name="ContractMessage",
        ),
        migrations.DeleteModel(
            name="Milestone",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.DeleteModel(
            name="Wallet",
        ),
        migrations.DeleteModel(
            name="WalletTransaction",
        ),
    ]
