# Generated by Django 4.2.17 on 2025-05-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0024_wallet_transaction_contract"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                    ("contract_funding", "Contract Funding"),
                    ("escrow_release", "Escrow Release"),
                    ("refund", "Refund"),
                    ("platform_fee", "Platform Fee"),
                ],
                max_length=20,
            ),
        ),
    ]
