# Generated by Django 4.2.17 on 2025-05-14 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0026_workroom_workroommessage_workroomattachment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="milestone",
            name="contract",
        ),
        migrations.RemoveField(
            model_name="workroom",
            name="contract",
        ),
        migrations.RemoveField(
            model_name="workroomattachment",
            name="message",
        ),
        migrations.RemoveField(
            model_name="workroomattachment",
            name="uploader",
        ),
        migrations.RemoveField(
            model_name="workroomattachment",
            name="workroom",
        ),
        migrations.RemoveField(
            model_name="workroommessage",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="workroommessage",
            name="workroom",
        ),
        migrations.DeleteModel(
            name="EscrowPayment",
        ),
        migrations.DeleteModel(
            name="Milestone",
        ),
        migrations.DeleteModel(
            name="Workroom",
        ),
        migrations.DeleteModel(
            name="WorkroomAttachment",
        ),
        migrations.DeleteModel(
            name="WorkroomMessage",
        ),
    ]
