# Generated by Django 4.2.17 on 2025-05-25 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0027_remove_milestone_contract_remove_workroom_contract_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "progress_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("review", "Under Review"),
                            ("revision_requested", "Revision Requested"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("progress_percentage", models.IntegerField(default=0)),
                (
                    "contract",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workroom",
                        to="jobapp.contract",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkroomMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Message"),
                            ("file", "File Attachment"),
                            ("milestone_update", "Milestone Update"),
                            ("system", "System Message"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_workroom_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="jobapp.workroom",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="WorkroomFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="workroom_files/")),
                ("filename", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField()),
                ("file_type", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("project_files", "Project Files"),
                            ("requirements", "Requirements"),
                            ("deliverables", "Deliverables"),
                            ("reference", "Reference Materials"),
                            ("other", "Other"),
                        ],
                        default="project_files",
                        max_length=20,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_workroom_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="jobapp.workroom",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkroomActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("message_sent", "Message Sent"),
                            ("file_uploaded", "File Uploaded"),
                            ("milestone_created", "Milestone Created"),
                            ("milestone_updated", "Milestone Updated"),
                            ("milestone_submitted", "Milestone Submitted"),
                            ("milestone_approved", "Milestone Approved"),
                            ("payment_released", "Payment Released"),
                            ("progress_updated", "Progress Updated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workroom_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="jobapp.workroom",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ProjectMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("due_date", models.DateTimeField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted for Review"),
                            ("approved", "Approved"),
                            ("revision_requested", "Revision Requested"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("deliverable_description", models.TextField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="jobapp.workroom",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="MilestonePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("released_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction_reference",
                    models.CharField(max_length=100, unique=True),
                ),
                (
                    "milestone",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="jobapp.projectmilestone",
                    ),
                ),
            ],
        ),
    ]
