# Generated by Django 4.2.17 on 2025-05-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0028_workroom_workroommessage_workroomfile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
