# Generated by Django 4.2.17 on 2025-06-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0029_make_email_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True,
                default="noreply@example.com",
                max_length=254,
                verbose_name="email address",
            ),
            preserve_default=False,
        ),
    ]
