# Base image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Install dependencies first
COPY package*.json ./
RUN npm install

# Copy the rest of the application
COPY . .

# Build the application
RUN npm run build

# Expose port
EXPOSE 3000

# Set host and port
ENV HOST=0.0.0.0
ENV PORT=3000

# Start the application
CMD [ "npm", "run", "dev" ]